# Generated by Django 6.0.7 on 2026-07-18 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('go', 'Go'), ('ruby', 'Ruby'), ('php', 'PHP'), ('csharp', 'C#'), ('other', 'Other / Auto-detect')], default='python', max_length=20)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, help_text='Overall code quality score, 0-100, from the AI review.', null=True)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('suggested_refactor', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=60)),
                ('ai_raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous/demo submissions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reviewer_co_created_27cde9_idx'), models.Index(fields=['language'], name='reviewer_co_languag_555377_idx')],
            },
        ),
    ]
